[package]
name = "library"
version = "0.1.0"
authors = ["taka"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.11"
ndarray = "0.13.0"
